### ISSUE TITLE
Small typo on blurb

### ISSUE THREAD

**Issue by xel** [standardebooks/charles-dickens_david-copperfield#1]
I couldn't find where to make a PR for this, so.....

On the blurb it says
"In David Copperfield we follow the life of the titular character as  **me** makes a life for himself in England. He finds himself in the care of a cold stepfather who sends him to boarding school, and from there embarks on a journey filled with characters and events that can only be called “Dickensian” in their colorful and just-barely-probable portrayals."

I believe the appropriate word is "he"?

**Comment by acabal** [comment]
Thanks, this should be fixed in e5a9499 and live on the site!

**Comment by xel** [comment]
Wow. that was quick.
Great job you're doing man
